
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action ArquivoAction;
	
	private global::Gtk.Action EditarAction;
	
	private global::Gtk.Action AbrirAction;
	
	private global::Gtk.Action SalvarAction;
	
	private global::Gtk.Action ArquivoAction1;
	
	private global::Gtk.Action EditarAction1;
	
	private global::Gtk.Action InserirAction;
	
	private global::Gtk.Action AutmatoAction;
	
	private global::Gtk.Action GramticaRegularAction;
	
	private global::Gtk.Action ExpressoRegularAction;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.MenuBar menubar2;
	
	private global::Gtk.Notebook notebook1;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.Label label1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.ArquivoAction = new global::Gtk.Action ("ArquivoAction", global::Mono.Unix.Catalog.GetString ("Arquivo"), null, null);
		this.ArquivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Arquivo");
		w1.Add (this.ArquivoAction, null);
		this.EditarAction = new global::Gtk.Action ("EditarAction", global::Mono.Unix.Catalog.GetString ("Editar"), null, null);
		this.EditarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Editar");
		w1.Add (this.EditarAction, null);
		this.AbrirAction = new global::Gtk.Action ("AbrirAction", global::Mono.Unix.Catalog.GetString ("Abrir"), null, null);
		this.AbrirAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Abrir");
		w1.Add (this.AbrirAction, null);
		this.SalvarAction = new global::Gtk.Action ("SalvarAction", global::Mono.Unix.Catalog.GetString ("Salvar"), null, null);
		this.SalvarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Salvar");
		w1.Add (this.SalvarAction, null);
		this.ArquivoAction1 = new global::Gtk.Action ("ArquivoAction1", global::Mono.Unix.Catalog.GetString ("Arquivo"), null, null);
		this.ArquivoAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Arquivo");
		w1.Add (this.ArquivoAction1, null);
		this.EditarAction1 = new global::Gtk.Action ("EditarAction1", global::Mono.Unix.Catalog.GetString ("Editar"), null, null);
		this.EditarAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Editar");
		w1.Add (this.EditarAction1, null);
		this.InserirAction = new global::Gtk.Action ("InserirAction", global::Mono.Unix.Catalog.GetString ("Inserir"), null, null);
		this.InserirAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Inserir");
		w1.Add (this.InserirAction, null);
		this.AutmatoAction = new global::Gtk.Action ("AutmatoAction", global::Mono.Unix.Catalog.GetString ("Autômato"), null, null);
		this.AutmatoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Autômato");
		w1.Add (this.AutmatoAction, null);
		this.GramticaRegularAction = new global::Gtk.Action ("GramticaRegularAction", global::Mono.Unix.Catalog.GetString ("Gramática Regular"), null, null);
		this.GramticaRegularAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Gramática Regular");
		w1.Add (this.GramticaRegularAction, null);
		this.ExpressoRegularAction = new global::Gtk.Action ("ExpressoRegularAction", global::Mono.Unix.Catalog.GetString ("Expressão Regular"), null, null);
		this.ExpressoRegularAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Expressão Regular");
		w1.Add (this.ExpressoRegularAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='ArquivoAction1' action='ArquivoAction1'/><menu name='EditarAction1' action='EditarAction1'/><menu name='InserirAction' action='InserirAction'><menuitem name='AutmatoAction' action='AutmatoAction'/><menuitem name='GramticaRegularAction' action='GramticaRegularAction'/><menuitem name='ExpressoRegularAction' action='ExpressoRegularAction'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox2.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w3 = new global::Gtk.Label ();
		w3.Visible = true;
		this.notebook1.Add (w3);
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Autômato");
		this.notebook1.SetTabLabel (w3, this.label2);
		this.label2.ShowAll ();
		// Notebook tab
		global::Gtk.Label w4 = new global::Gtk.Label ();
		w4.Visible = true;
		this.notebook1.Add (w4);
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Gramática Regular");
		this.notebook1.SetTabLabel (w4, this.label3);
		this.label3.ShowAll ();
		// Notebook tab
		global::Gtk.Label w5 = new global::Gtk.Label ();
		w5.Visible = true;
		this.notebook1.Add (w5);
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Expressão Regular");
		this.notebook1.SetTabLabel (w5, this.label1);
		this.label1.ShowAll ();
		this.vbox2.Add (this.notebook1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook1]));
		w6.Position = 1;
		this.Add (this.vbox2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 445;
		this.DefaultHeight = 306;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
